# Generated by Django 3.2.5 on 2021-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogmodel_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
